### ISSUE TITLE
Errors - only archives one month and then fails

### ISSUE THREAD

**Issue by 2600box** [oliyh/tinybeans-archive#2]
Thanks for this tool. I am having some trouble with it however. has tinybeans changed something, or is it me?

```
lein archive <API_KEY>
Archiving tinybeans entries for journal <journal> into archive
Feb. 15, 2020 10:27:18 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:18 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:18 GMT
Feb. 15, 2020 10:27:18 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:18 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:18 GMT
Fetching 2018-6
Feb. 15, 2020 10:27:19 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:19 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:19 GMT
Feb. 15, 2020 10:27:19 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:19 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:19 GMT
Fetching 2018-7
Feb. 15, 2020 10:27:20 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:20 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:20 GMT
Feb. 15, 2020 10:27:20 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:20 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:20 GMT
Fetching 2018-8
Feb. 15, 2020 10:27:20 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:20 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:20 GMT
Feb. 15, 2020 10:27:20 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:20 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:20 GMT
Fetching 2018-9
Feb. 15, 2020 10:27:21 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:21 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:21 GMT
Feb. 15, 2020 10:27:21 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:21 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:21 GMT
Fetching 2018-10
Feb. 15, 2020 10:27:21 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:21 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:21 GMT
Feb. 15, 2020 10:27:21 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:21 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:21 GMT
Fetching 2018-11
Feb. 15, 2020 10:27:22 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:22 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:22 GMT
Feb. 15, 2020 10:27:22 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:22 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:22 GMT
Fetching 2018-12
Feb. 15, 2020 10:27:22 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:22 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:22 GMT
Feb. 15, 2020 10:27:22 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:22 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:22 GMT
Fetching 2019-1
Feb. 15, 2020 10:27:23 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:23 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:23 GMT
Feb. 15, 2020 10:27:23 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:23 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:23 GMT
Fetching 2019-2
Feb. 15, 2020 10:27:23 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:23 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:23 GMT
Feb. 15, 2020 10:27:23 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:23 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:23 GMT
Fetching 2019-3
Feb. 15, 2020 10:27:24 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:24 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:24 GMT
Feb. 15, 2020 10:27:24 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:24 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:24 GMT
Fetching 2019-4
Feb. 15, 2020 10:27:24 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:24 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:24 GMT
Feb. 15, 2020 10:27:24 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:24 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:24 GMT
Fetching 2019-5
Feb. 15, 2020 10:27:25 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:25 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:25 GMT
Feb. 15, 2020 10:27:25 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:25 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:25 GMT
Fetching 2019-6
Feb. 15, 2020 10:27:25 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:25 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:25 GMT
Feb. 15, 2020 10:27:25 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:25 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:25 GMT
Fetching 2019-7
Feb. 15, 2020 10:27:25 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:25 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:25 GMT
Feb. 15, 2020 10:27:25 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:25 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:25 GMT
Fetching 2019-8
Feb. 15, 2020 10:27:26 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:26 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:26 GMT
Feb. 15, 2020 10:27:26 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:26 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:26 GMT
Fetching 2019-9
Feb. 15, 2020 10:27:26 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:26 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:26 GMT
Feb. 15, 2020 10:27:26 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:26 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:26 GMT
Fetching 2019-10
Feb. 15, 2020 10:27:27 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:27 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:27 GMT
Feb. 15, 2020 10:27:27 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:27 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:27 GMT
Fetching 2019-11
Feb. 15, 2020 10:27:27 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:27 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:27 GMT
Feb. 15, 2020 10:27:27 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:27 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:27 GMT
Fetching 2019-12
Feb. 15, 2020 10:27:28 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:28 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:28 GMT
Feb. 15, 2020 10:27:28 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:28 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:28 GMT
Fetching 2020-1
Feb. 15, 2020 10:27:28 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:28 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:28 GMT
Feb. 15, 2020 10:27:28 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:28 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:28 GMT
Fetching 2020-2
Feb. 15, 2020 10:27:28 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_ERRORS=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:28 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:28 GMT
Feb. 15, 2020 10:27:28 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=0; Expires=Sat, 15 Feb 2020 02:27:28 GMT; Path=/". Invalid 'expires' attribute: Sat, 15 Feb 2020 02:27:28 GMT
Found 669 entries for <kids_name>
Unable to archive entry {:deleted false, :caption Weight 3.15kg, :day 20, :children [{:childId 986223}], :clientRef <snip>, :journalId <journal>, :month 6, :type TEXT, :longitude 0.0, :privateMode false, :year 2018, :lastUpdatedTimestamp <snip>, :blobs {:o https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-o.png, :o2 https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-o2.png, :t https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-t.png, :s https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-s.png, :s2 https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-s2.png, :m https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-m.png, :l https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-l.png, :p https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-p.png}, :id <snip>, :iso-date 2018-07-20, :userId 2534508, :latitude 0.0, :uuid <snip>, :URL https://tinybeans.com/api/1/journals/<journal>/entries/<snip>, :timestamp <snip>} #error {
 :cause clj-http: status 403
 :data {:request-time 810, :repeatable? false, :protocol-version {:name HTTP, :major 1, :minor 1}, :streaming? true, :chunked? true, :type :clj-http.client/unexceptional-status, :reason-phrase Forbidden, :headers {x-amz-request-id <snip>, x-amz-id-2 <snip>, Content-Type application/xml, Transfer-Encoding chunked, Date Sat, 15 Feb 2020 02:27:29 GMT, Server AmazonS3, Connection close}, :orig-content-encoding nil, :status 403, :length -1, :body #object[[B 0x2cc04e54 [B@2cc04e54], :trace-redirects []}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message clj-http: status 403
   :data {:request-time 810, :repeatable? false, :protocol-version {:name HTTP, :major 1, :minor 1}, :streaming? true, :chunked? true, :type :clj-http.client/unexceptional-status, :reason-phrase Forbidden, :headers {x-amz-request-id <snip>, x-amz-id-2 <snip>, Content-Type application/xml, Transfer-Encoding chunked, Date Sat, 15 Feb 2020 02:27:29 GMT, Server AmazonS3, Connection close}, :orig-content-encoding nil, :status 403, :length -1, :body #object[[B 0x2cc04e54 [B@2cc04e54], :trace-redirects []}
   :at [slingshot.support$stack_trace invoke support.clj 201]}]
 :trace
 [[slingshot.support$stack_trace invoke support.clj 201]
  [clj_http.client$exceptions_response invokeStatic client.clj 239]
  [clj_http.client$exceptions_response invoke client.clj 230]
  [clj_http.client$wrap_exceptions$fn__3713 invoke client.clj 248]
  [clj_http.client$wrap_accept$fn__3959 invoke client.clj 724]
  [clj_http.client$wrap_accept_encoding$fn__3966 invoke client.clj 746]
  [clj_http.client$wrap_content_type$fn__3953 invoke client.clj 707]
  [clj_http.client$wrap_form_params$fn__4062 invoke client.clj 948]
  [clj_http.client$wrap_nested_params$fn__4084 invoke client.clj 983]
  [clj_http.client$wrap_method$fn__4020 invoke client.clj 882]
  [clj_http.cookies$wrap_cookies$fn__2066 invoke cookies.clj 131]
  [clj_http.links$wrap_links$fn__3489 invoke links.clj 63]
  [clj_http.client$wrap_unknown_host$fn__4092 invoke client.clj 1009]
  [clj_http.client$request_STAR_ invokeStatic client.clj 1181]
  [clj_http.client$request_STAR_ invoke client.clj 1174]
  [clj_http.client$get invokeStatic client.clj 1187]
  [clj_http.client$get doInvoke client.clj 1183]
  [clojure.lang.RestFn invoke RestFn.java 423]
  [tinybeans_archive.core$archive_image invokeStatic core.clj 58]
  [tinybeans_archive.core$archive_image invoke core.clj 55]
  [tinybeans_archive.core$archive_entry invokeStatic core.clj 111]
  [tinybeans_archive.core$archive_entry invoke core.clj 108]
  [clojure.core$partial$fn__5561 invoke core.clj 2616]
  [clojure.core$pmap$fn__8105$fn__8106 invoke core.clj 6942]
  [clojure.core$binding_conveyor_fn$fn__5476 invoke core.clj 2022]
  [clojure.lang.AFn call AFn.java 18]
  [java.util.concurrent.FutureTask run FutureTask.java 264]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1128]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 628]
  [java.lang.Thread run Thread.java 835]]}
Unable to archive entry {:deleted false, :caption Weight 3.28kg , :day 14, :children [{:childId 986223}], :clientRef <snip>, :journalId <journal>, :month 6, :type TEXT, :longitude 0.0, :privateMode false, :year 2018, :lastUpdatedTimestamp <snip>, :blobs {:o https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-o.png, :o2 https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-o2.png, :t https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-t.png, :s https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-s.png, :s2 https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-s2.png, :m https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-m.png, :l https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-l.png, :p https://tinybeans-public.s3-us-west-2.amazonaws.com/images/textMoment-p.png}, :id <snip>, :iso-date 2018-07-20, :userId 2534508, :latitude 0.0, :uuid <snip>, :URL https://tinybeans.com/api/1/journals/<journal>/entries/<snip>, :timestamp <snip>} #error {
 :cause clj-http: status 403
 :data {:request-time 871, :repeatable? false, :protocol-version {:name HTTP, :major 1, :minor 1}, :streaming? true, :chunked? true, :type :clj-http.client/unexceptional-status, :reason-phrase Forbidden, :headers {x-amz-request-id <snip>, x-amz-id-2 <snip>=, Content-Type application/xml, Transfer-Encoding chunked, Date Sat, 15 Feb 2020 02:27:28 GMT, Server AmazonS3, Connection close}, :orig-content-encoding nil, :status 403, :length -1, :body #object[[B 0x585147d5 [B@585147d5], :trace-redirects []}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message clj-http: status 403
   :data {:request-time 871, :repeatable? false, :protocol-version {:name HTTP, :major 1, :minor 1}, :streaming? true, :chunked? true, :type :clj-http.client/unexceptional-status, :reason-phrase Forbidden, :headers {x-amz-request-id <snip>, x-amz-id-2 <snip>=, Content-Type application/xml, Transfer-Encoding chunked, Date Sat, 15 Feb 2020 02:27:28 GMT, Server AmazonS3, Connection close}, :orig-content-encoding nil, :status 403, :length -1, :body #object[[B 0x585147d5 [B@585147d5], :trace-redirects []}
   :at [slingshot.support$stack_trace invoke support.clj 201]}]
 :trace
 [[slingshot.support$stack_trace invoke support.clj 201]
  [clj_http.client$exceptions_response invokeStatic client.clj 239]
  [clj_http.client$exceptions_response invoke client.clj 230]
  [clj_http.client$wrap_exceptions$fn__3713 invoke client.clj 248]
  [clj_http.client$wrap_accept$fn__3959 invoke client.clj 724]
  [clj_http.client$wrap_accept_encoding$fn__3966 invoke client.clj 746]
  [clj_http.client$wrap_content_type$fn__3953 invoke client.clj 707]
  [clj_http.client$wrap_form_params$fn__4062 invoke client.clj 948]
  [clj_http.client$wrap_nested_params$fn__4084 invoke client.clj 983]
  [clj_http.client$wrap_method$fn__4020 invoke client.clj 882]
  [clj_http.cookies$wrap_cookies$fn__2066 invoke cookies.clj 131]
  [clj_http.links$wrap_links$fn__3489 invoke links.clj 63]
  [clj_http.client$wrap_unknown_host$fn__4092 invoke client.clj 1009]
  [clj_http.client$request_STAR_ invokeStatic client.clj 1181]
  [clj_http.client$request_STAR_ invoke client.clj 1174]
  [clj_http.client$get invokeStatic client.clj 1187]
  [clj_http.client$get doInvoke client.clj 1183]
  [clojure.lang.RestFn invoke RestFn.java 423]
  [tinybeans_archive.core$archive_image invokeStatic core.clj 58]
  [tinybeans_archive.core$archive_image invoke core.clj 55]
  [tinybeans_archive.core$archive_entry invokeStatic core.clj 111]
  [tinybeans_archive.core$archive_entry invoke core.clj 108]
  [clojure.core$partial$fn__5561 invoke core.clj 2616]
  [clojure.core$pmap$fn__8105$fn__8106 invoke core.clj 6942]
  [clojure.core$binding_conveyor_fn$fn__5476 invoke core.clj 2022]
  [clojure.lang.AFn call AFn.java 18]
  [java.util.concurrent.FutureTask run FutureTask.java 264]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1128]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 628]
  [java.lang.Thread run Thread.java 835]]}
Exception in thread "main" java.lang.NullPointerException, compiling:(/private/var/folders/yh/<snip>/T/form-<snip>.clj:1:126)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
	at tinybeans_archive.core$relative.invokeStatic(core.clj:153)
	at tinybeans_archive.core$relative.invoke(core.clj:152)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at tinybeans_archive.core$month_page$iter__4959__4963$fn__4964.invoke(core.clj:174)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:706)
	at clojure.core$next__5108.invokeStatic(core.clj:64)
	at clojure.core$str$fn__5188.invoke(core.clj:557)
	at clojure.core$str.invokeStatic(core.clj:555)
	at clojure.core$str.doInvoke(core.clj:544)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at tinybeans_archive.core$month_page.invokeStatic(core.clj:164)
	at tinybeans_archive.core$month_page.invoke(core.clj:163)
	at tinybeans_archive.core$archive_month.invokeStatic(core.clj:186)
	at tinybeans_archive.core$archive_month.invoke(core.clj:177)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at clojure.core$map$fn__5587.invoke(core.clj:2747)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$sort.invokeStatic(core.clj:3105)
	at clojure.core$sort_by.invokeStatic(core.clj:3111)
	at clojure.core$sort_by.invokeStatic(core.clj:3111)
	at clojure.core$sort_by.invoke(core.clj:3111)
	at tinybeans_archive.core$year_page.invokeStatic(core.clj:195)
	at tinybeans_archive.core$year_page.invoke(core.clj:189)
	at tinybeans_archive.core$archive_year.invokeStatic(core.clj:211)
	at tinybeans_archive.core$archive_year.invoke(core.clj:202)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at clojure.core$map$fn__5587.invoke(core.clj:2747)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$sort.invokeStatic(core.clj:3105)
	at clojure.core$sort_by.invokeStatic(core.clj:3111)
	at clojure.core$sort_by.invokeStatic(core.clj:3111)
	at clojure.core$sort_by.invoke(core.clj:3111)
	at tinybeans_archive.core$home_page.invokeStatic(core.clj:220)
	at tinybeans_archive.core$home_page.invoke(core.clj:214)
	at tinybeans_archive.core$archive.invokeStatic(core.clj:252)
	at tinybeans_archive.core$archive.invoke(core.clj:227)
	at tinybeans_archive.core$archive.invokeStatic(core.clj:231)
	at tinybeans_archive.core$archive.invoke(core.clj:227)
	at tinybeans_archive.main$_main.invokeStatic(main.clj:9)
	at tinybeans_archive.main$_main.doInvoke(main.clj:5)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:385)
	at user$eval149.invokeStatic(form-<snip>.clj:1)
	at user$eval149.invoke(form-<snip>.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
```

**Comment by oliyh** [comment]
Hi,

Looks like it fails catastrophically when coming across a weight entry - we only use it for photos and video so hadn't come across them before. Should be a simple fix.

**Comment by oliyh** [comment]
Hi,

Try again with the latest code now - hope it works for you.

**Comment by 2600box** [comment]
Seems to do the job. cheers
